<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <!-- Include all .toml files as embedded resources (so we can dynamically load them at runtime) -->
        <EmbeddedResource Include="**\*.toml" />

        <!-- Specify invariant files that are fed into the generator (Echoes.Generator) -->
        <AdditionalFiles Include="Translations\Strings.toml" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Echoes" Version="0.4.1" />
      <PackageReference Include="Echoes.Generator" Version="0.4.1" />
    </ItemGroup>
    
</Project>
