<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
		<OutputType>exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

	<PropertyGroup Condition="'$(OS)' == 'WINDOWS_NT'">
		<TargetFrameworks>net8.0-windows10.0.19041.0</TargetFrameworks>

		<WindowsSdkPackageVersion>10.0.19041.41</WindowsSdkPackageVersion>
		<CsWinRTWindowsMetadata>10.0.19041.41</CsWinRTWindowsMetadata>
	</PropertyGroup>

	<PropertyGroup Condition="'$(OS)' == 'UNIX'">
		<TargetFrameworks>net8.0</TargetFrameworks>
	</PropertyGroup>
	
    <ItemGroup>
        <Folder Include="Controls\" />
        <Folder Include="Models\" />
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.5" />
        <PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.5">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="FluentAvaloniaUI" Version="2.4.0" />
    </ItemGroup>

    <ItemGroup>
      <EditorConfigFiles Remove=".editorconfig" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HASS.Agent.Base\HASS.Agent.Base.csproj" />
    </ItemGroup>
</Project>
