<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>x64;x86</Platforms>
	</PropertyGroup>

	<PropertyGroup Condition="'$(OS)' == 'WINDOWS_NT'">
		<TargetFrameworks>net9.0-windows10.0.19041.0</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(OS)' == 'UNIX'">
		<TargetFrameworks>net9.0</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Amadeo.HADotNet.Core" Version="0.2.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
		<PackageReference Include="MQTTnet" Version="5.0.1.1416" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
		<PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
		<EditorConfigFiles Remove="D:\Programowanie\Visual CS\Projects\HASS.Agent.v3\src\HASS.Agent.Base\.editorconfig" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HASS.Agent.Contracts\HASS.Agent.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net9.0-windows10.0.19041.0' ">
		<ProjectReference Include="..\HASS.Agent.Base.Windows\HASS.Agent.Base.Windows.csproj" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net9.0' ">
		<ProjectReference Include="..\HASS.Agent.Base.Linux\HASS.Agent.Base.Linux.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Models\Entity\" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
